export const nigeriaStates = [
  { name: "Abia", shortName: "AB" },
  { name: "Adamawa", shortName: "AD" },
  { name: "Akwa Ibom", shortName: "AK" },
  { name: "Anambra", shortName: "AN" },
  { name: "Bauchi", shortName: "BA" },
  { name: "Bayelsa", shortName: "BY" },
  { name: "Benue", shortName: "BE" },
  { name: "Borno", shortName: "BO" },
  { name: "Cross River", shortName: "CR" },
  { name: "Delta", shortName: "DE" },
  { name: "Ebonyi", shortName: "EB" },
  { name: "Edo", shortName: "ED" },
  { name: "Ekiti", shortName: "EK" },
  { name: "Enugu", shortName: "EN" },
  { name: "Gombe", shortName: "GO" },
  { name: "Imo", shortName: "IM" },
  { name: "Jigawa", shortName: "JI" },
  { name: "Kaduna", shortName: "KD" },
  { name: "Kano", shortName: "KN" },
  { name: "Katsina", shortName: "KT" },
  { name: "Kebbi", shortName: "KE" },
  { name: "Kogi", shortName: "KO" },
  { name: "Kwara", shortName: "KW" },
  { name: "Lagos", shortName: "LA" },
  { name: "Nasarawa", shortName: "NA" },
  { name: "Niger", shortName: "NI" },
  { name: "Ogun", shortName: "OG" },
  { name: "Ondo", shortName: "ON" },
  { name: "Osun", shortName: "OS" },
  { name: "Oyo", shortName: "OY" },
  { name: "Plateau", shortName: "PL" },
  { name: "Rivers", shortName: "RI" },
  { name: "Sokoto", shortName: "SO" },
  { name: "Taraba", shortName: "TA" },
  { name: "Yobe", shortName: "YO" },
  { name: "Zamfara", shortName: "ZA" },
];
